services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: travelers_client
    restart: unless-stopped
    command: ['python', 'src']
    ports:
      # Websocket port
      - '8765:8765'
    volumes:
      - ./src:/src
